apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: django-postgres
type: Opaque
data:
  user: ZGphbmdv #must be in base64
  password: MWEyNmQxZzI2ZDFnZXNiP2U3ZGVzYj9lN2Q= #must be in base64
  
  #echo -n "<user or password string>" | base64