apiVersion: v1
kind: Service
metadata:
  name: django-application-tracker-service
  namespace: django-appname
spec:
  selector:
    pod: django-application-tracker
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000